language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
env:
  - PROJECT_NAME = wordup
  - PROJECT_NAME = app
script:
  - chmod +x ./gradlew
  - ./gradlew clean $PROJECT_NAME:ktlintCheck


