language: android
dist: trusty
before_install:
  - chmod +x gradlew
android:
  components:
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
env:
  - PROJECT_NAME=wordup-core
  - PROJECT_NAME=example
script:
  - ./gradlew clean $PROJECT_NAME:ktlintCheck


