language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-28
script:
   - chmod +x ./gradlew build connectedCheck
    
