name: debug-actions
on:
  push:
    branches-ignore:
      - 'master'
      - 'development'
jobs:
  check-ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Caching gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Check ktlint on wordup-core
        run: ./gradlew wordup-core:ktlintCheck
      - name:  Check ktlint on example
        run: ./gradlew example:ktlintCheck